INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Kenneth","Adams","38","black","3D printing,Shoemaking");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Ryan","Reed","36","green","LARPing,Kayaking");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Arthur","Thomas","42","red","Social media,Herp keeping");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Roger","Harris","27","white","Singing,Writing");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Brandon","Bennett","40","brown","Photography,Sculpting");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Lisa","Wright","43","red","Swimming,Rail transport modeling");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Joe","Washington","45","pink","Model building,Podcast hosting");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Ruth","Russell","16","white","Hiking,BASE jumping");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Ann","Young","35","purple","Digital arts,Origami");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Rebecca","Nelson","36","brown","Foreign language learning,Juggling");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Janice","Lopez","43","pink","Quilting,Model building");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Stephanie","Cook","19","pink","Orienteering,Longboarding");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Debra","Bryant","19","brown","Walking,Model engineering");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Sarah","Peterson","38","black","Hobby horsing,Candle making");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Charles","Taylor","17","black","BMX,Rafting");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Peter","Cooper","54","purple","Car fixing & building,Orienteering");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Judith","Jenkins","46","yellow","Cryptography,Whittling");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Susan","Stewart","47","blue","Brazilian jiu-jitsu,Herbalism");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Scott","James","41","blue","Flower growing,Fashion");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Anna","Hernandez","20","white","Survivalism,Kendama");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Ruby","Cox","34","yellow","Graffiti,Beatboxing");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Aaron","Scott","55","green","Topiary,Fashion design");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Nicholas","Kelly","57","green","Video editing,Lock picking");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Andrew","Roberts","46","green","Drama,Herbalism");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Ernest","Wilson","29","brown","Lock picking,Sailing");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Theresa","Parker","15","purple","Bodybuilding,Meteorology");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Billy","Thompson","33","yellow","Calligraphy,Thrifting");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Steven","Rogers","35","orange","Stamp collecting,Reading");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Jonathan","Barnes","31","pink","Djing,Hobby horsing");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Marilyn","Alexander","53","white","Skiing,Leather crafting");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Jane","Robinson","48","pink","Robot combat,Cue sports");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Bruce","Turner","36","blue","Scuba diving,Juggling");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Juan","Miller","48","brown","Foraging,Distro Hopping");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Heather","Mitchell","40","white","Creative writing,Breadmaking");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Jesse","Gray","57","orange","Martial arts,Karaoke");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Joshua","Moore","21","yellow","Knot tying,Vegetable farming");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Anthony","Coleman","31","green","Flag football,Soccer");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Kimberly","Sanchez","36","brown","Astronomy,Needlepoint");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Bonnie","Bailey","44","red","Hooping,Painting");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Victor","Powell","29","green","Thrifting,Topiary");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Jacqueline","Sanders","24","white","Pressed flower craft,Rapping");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Karen","Smith","36","red","Weight training,Mushroom hunting/mycology");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Janet","Walker","35","blue","Swimming,Caving");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Randy","Williams","52","blue","Coloring,Basketball");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Raymond","Ramirez","49","black","Table tennis,Weaving");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Mildred","Price","17","red","High-power rocketry,Longboarding");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Clarence","Rivera","41","blue","Photography,Kitesurfing");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Thomas","Howard","46","blue","Beekeeping,Survivalism");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Cheryl","Rodriguez","55","pink","Robot combat,Metal detecting");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Beverly","Torres","42","pink","Jogging,Flag football");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Anne","Morris","24","green","Rugby,Orienteering");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Catherine","Edwards","33","black","Birdwatching,Origami");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Amanda","Hughes","29","green","Foraging,Table tennis");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Diana","Diaz","51","red","Cross-stitch,Painting");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Steve","Hill","20","brown","Skimboarding,Social media");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Gerald","Collins","24","green","Cosplaying,LARPing");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Donald","Patterson","24","purple","Parkour,Mountaineering");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Carlos","Griffin","52","pink","3D printing,Couponing");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Barbara","Richardson","40","orange","Furniture building,Aquascaping");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Christina","Johnson","55","red","Mountaineering,Crocheting");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("John","Lee","16","yellow","Lapidary,Slacklining");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Albert","Martinez","59","yellow","Kayaking,Crocheting");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Kelly","Campbell","33","green","Freestyle football,Skiing");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Brenda","Butler","50","green","BMX,Photography");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Kevin","Henderson","20","yellow","Stand-up comedy,Hydroponics");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Sara","Hall","41","red","Skiing,Writing");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Russell","Brooks","54","blue","Lock picking,Acrobatics");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("David","Watson","38","yellow","Sculpting,Baseball");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Eugene","Gonzalez","51","yellow","Sketching,Pressed flower craft");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Evelyn","Bell","17","brown","Yoga,Skydiving");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Annie","Jones","21","blue","Pet adoption & fostering,Basketball");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Gloria","Evans","24","brown","Basketball,Astronomy");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Nicole","Perez","58","brown","Sun bathing,Taekwondo");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Laura","Anderson","32","white","Whittling,Hula hooping");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Wanda","Foster","21","green","Sketching,Drawing");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Fred","Baker","57","green","Bowling,Shooting");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Tammy","King","48","black","Fishing,Powerlifting");
INSERT INTO `person` (`first_name`,`last_name`,`age`,`favourite_colour`,`hobby`) VALUES("Chris","Green","42","pink","Mountaineering,Wikipedia editing");
